blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>', views.blog_detail, name='blog_detail'),
    path('delete/<int:id>', views.comment_delete, name='comment_delete'),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workouts.urls'), name="workouts"),
    path('blog', include('blog.urls'), name="blog"),

    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workouts/urls.py
from django.urls import path

from . import views

app_name = 'workouts'

urlpatterns = [
    path('', views.index, name='home'),
    path('exercise/<int:exercise_id>',
         views.exercise_detail, name='exercise_detail'),

    path('program', views.program, name='program'),
    path('program/<slug:slug>', views.program_detail, name='program_detail'),
    path('coach', views.coach, name='coach'),
    path('coach/<int:coach_id>', views.coach_detail, name='coach_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),

    # Members
    path('register', views.register_page, name='register_page'),
    path('login', views.login_page, name='login_page'),
    path('logout', views.logout_page, name='logout_page'),
    path('member', views.member_page, name='member_page'),
    path('create_workout', views.create_workout, name='create_workout'),
    path('update_workout/<int:id>', views.update_workout, name='update_workout'),
]

workouts/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.fields import DateField

from django.utils.safestring import mark_safe
from tinymce import HTMLField


class Category(models.Model):
    TYPE = (
        ('Body Building', 'Body Building'),
        ('Aerobic', 'Aerobic'),
        ('Weight Lifting', 'Weight Lifting'),
        ('Yoga', 'Yoga'),
        ('Crossfit', 'Crossfit'),
        ('Body Fit', 'Body Fit'),
        ('Gym', 'Gym'),
    )
    title = models.CharField(max_length=100, choices=TYPE)
    slug = models.SlugField(max_length=100, blank=True, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='program')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('workouts:program_detail', kwargs={
            'slug': self.slug
        })


class Exercise(models.Model):
    image = models.ImageField(upload_to='exercises')
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = HTMLField()

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('workouts:exercise_detail', kwargs={
            'exercise_id': self.id
        })


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='members')

    def __str__(self) -> str:
        return self.user.username


class Workout(models.Model):
    STATUS = (
        ('In progress', 'In progress'),
        ('Finished', 'Finished')
    )
    name = models.CharField(max_length=100)
    member = models.ForeignKey(
        Member, null=True, blank=True, on_delete=models.CASCADE)
    date_of_training = DateField()
    exercise = models.ManyToManyField(Exercise)
    status = models.CharField(
        max_length=100, null=True, blank=True, choices=STATUS)

    def __str__(self) -> str:
        return self.name


class Coach(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(blank=True, null=True, upload_to='coach')
    category = models.ManyToManyField(Category)
    bio = HTMLField()

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" style="width: 250px;" />')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('workouts:coach_detail', kwargs={
            'coach_id': self.id
        })

    @property
    def get_comments(self):
        return self.comments_coach.all().order_by('-created')


class Comments_coach(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    coach = models.ForeignKey(
        Coach, related_name='comments_coach', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} on {self.coach.name}"


class Insta_Gallery(models.Model):
    image = models.ImageField(upload_to='insta_gallery')
    created = models.DateTimeField(auto_now_add=True)

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" style="width: 250px;" />')


class Slider(models.Model):
    image = models.ImageField(upload_to='banner')
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" style="width: 250px;" />')


class Banner(models.Model):
    PAGES = (
        ('about', 'about'),
        ('contact', 'contact'),
        ('blog', 'blog'),
        ('coach', 'coach'),
        ('program', 'program'),
    )
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='banner')
    created = models.DateTimeField(auto_now_add=True)
    page = models.CharField(max_length=100, choices=PAGES)

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" style="width: 250px;" />')

    def __str__(self) -> str:
        return self.title

workouts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Workout, Member, Comments_coach


class DateInput(forms.DateInput):
    input_type = 'date'


class WorkoutForm(ModelForm):
    def __init__(self, user, *arg, **kwargs):
        super(WorkoutForm, self).__init__(*arg, **kwargs)
        self.fields['member'].queryset = Member.objects.filter(
            user_id=user)

    class Meta:
        model = Workout
        fields = '__all__'
        widget = {'date_of_training': DateInput()}


class MemberForm(ModelForm):

    class Meta:
        model = Member
        fields = ['profile_pic']


class Comments_coachForm(forms.ModelForm):
    content = forms.CharField(label='Message', widget=forms.Textarea(attrs={
        'class': 'form-control',
        'id': 'usercomment',
        'rows': '10',
        'cols': '3',
    }))

    class Meta:
        model = Comments_coach
        fields = ['content', ]

workouts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from django.db.models import Count

from .models import Exercise, Member, Workout, Banner, Coach, Category, Insta_Gallery
from blog.models import Post
from .forms import WorkoutForm, MemberForm, Comments_coachForm


def index(request):
    recent_posts = Post.objects.all().order_by('-created')[:3]

    # Display categories on homepage sorted by number of exercices desc
    most_categories = Category.objects.annotate(
        number_of_exercises=Count('exercise'))
    categories = {}
    for cat in most_categories:
        # get the category only if it has exercises in it
        if cat.number_of_exercises > 0:
            categories[cat.title] = [cat.number_of_exercises,
                                     cat.slug, cat.image, cat.description]
    # dict sorted by number of exercises
    sorted_categories = sorted(
        categories.items(), key=lambda x: x[1][0], reverse=True)

    # get pics from insta_gallery model
    gallery = Insta_Gallery.objects.all().order_by('-created')[:7]
    context = {
        'recent_posts': recent_posts,
        'categories': sorted_categories[:4],
        'gallery': gallery
    }
    return render(request, 'index.html', context)


def exercise_detail(request, exercise_id):
    exercise = get_object_or_404(Exercise, id=exercise_id)
    context = {
        'exercise': exercise
    }
    return render(request, 'exercise_detail.html', context)


def member_page(request):
    member = Member.objects.get(user=request.user)
    workouts = member.workout_set.all()
    total_workouts = workouts.count()
    in_progres = member.workout_set.filter(status='In progress').count()
    finished = member.workout_set.filter(status='Finished').count()
    form = MemberForm()
    if request.method == 'POST':
        form = MemberForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            form.save()

    context = {
        'member': member,
        'workouts': workouts,
        'total_workouts': total_workouts,
        'in_progres': in_progres,
        'finished': finished,
        'form': form,
    }
    return render(request, 'user/member.html', context)


def create_workout(request):
    member = Member.objects.get(user=request.user)
    form = WorkoutForm(request.user)
    if request.method == 'POST':
        form = WorkoutForm(request.user, request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('workouts:member_page')
    context = {
        'form': form
    }
    return render(request, 'workout_form.html', context)


def update_workout(request, id):
    workout = Workout.objects.get(id=id)
    form = WorkoutForm(request.user, instance=workout)

    if request.method == 'POST':
        form = WorkoutForm(request.user, request.POST, instance=workout)

        if form.is_valid():
            form.instance.workout = workout
            form.save()
            return redirect('workouts:member_page')
    context = {
        'form': form
    }
    return render(request, 'workout_form.html', context)


def program(request):
    categories = Category.objects.all().order_by('title')
    context = {
        'categories': categories,
        'banner': Banner.objects.filter(page='program').first
    }
    return render(request, 'program.html', context)


def program_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    exercises = Exercise.objects.filter(category=category)
    context = {
        'category': category,
        'exercises': exercises
    }
    return render(request, 'program_detail.html', context)


def coach(request):
    coaches = Coach.objects.all().order_by('name')
    context = {
        'coaches': coaches,
        'banner': Banner.objects.filter(page='coach').first,
    }
    return render(request, 'coach.html', context)


def coach_detail(request, coach_id):
    coach = get_object_or_404(Coach, id=coach_id)
    form = Comments_coachForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.user = request.user
            form.instance.coach = coach
            form.save()
            return redirect(reverse('workouts:coach_detail', kwargs={
                'coach_id': coach.id
            }))
    context = {
        'coach': coach,
        'form': form,
        'counter_comments': coach.comments_coach.count()
    }
    return render(request, 'coach_detail.html', context)


def about(request):
    return render(request, 'about.html', {'banner': Banner.objects.filter(page='about').first})


def contact(request):
    return render(request, 'contact.html', {'banner': Banner.objects.filter(page='contact').first})


def register_page(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Member.objects.create(user=user)
            return redirect('workouts:login_page')

    context = {
        'form': form
    }
    return render(request, 'user/register.html', context)


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('workouts:home')

    return render(request, 'user/login.html')


def logout_page(request):
    logout(request)
    return redirect('workouts:login_page')

templates/banner.html
<section class="hero-wrap js-fullheight" style="background-image: url({{ content.image.url }}); height: 661px;">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center"
            style="height: 661px;">
            {% if content.title %}
            <div class="col-md-9 ftco-animate text-center fadeInUp ftco-animated">
                <h1 class="mb-3 bread">{{ content.title|title }}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'blog:home' %}">Home</a></span>
                    <span>{% if content.page %}{{ content.page }}{% endif %}</span>
                </p>
            </div>
            {% endif %}
        </div>
    </div>
</section>

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}

<html lang="en">

<head>
  {% include 'head.html' %}
</head>

<body>
  {% include 'nav.html' %}
  {% block content %}
  {% endblock content %}

  {% show_latest_posts %}

  {% include 'scripts.html' %}
</body>

</html>

templates/bodybuilding.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>
<center>
  <h1>Body Building Exercises</h1>
</center>
<div class="row">

  {% for exercise in bodyBuildingExercises%}
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="{{ exercise.image.url }}" height="300px" width="250px" alt="Card image cap">
    <div class="card-body text-center">
      <h5 class="card-title">{{ exercise.name }}</h5>
      <a href="{{ exercise.get_absolute_url }}" class="btn btn-primary">See content</a>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/coach_detail.html
{% extends 'base.html' %}


{% block content %}

{% include 'banner.html' with content=coach%}

<section class="ftco-degree">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate fadeInUp ftco-animated">
                <h2 class="mb-3">{{ coach.name|title }}</h2>
                {{ coach.bio|safe }}

                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for cat in coach.category.all %}
                        <a href="#" class="tag-cloud-link">{{cat}}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ counter_comments }} Comment{{ counter_comments|pluralize}}</h3>
                    <ul class="comment-list">
                        {% for comment in coach.comments_coach.all %}
                        <li class="comment">

                            <div class="vcard bio">
                                <img src="{% if comment.user.member.profile_pic %}{{ comment.user.member.profile_pic.url }}{%endif%}"
                                    alt="Image placeholder">
                            </div>

                            <div class="comment-body ">
                                <h3>{{ comment.user }}</h3>
                                <div class="meta">{{ comment.created }}</div>
                                <p>{{ comment.content }}</p>
                                {% if request.user == comment.user or request.user.is_staff %}
                                <div class="text-right">
                                    <a class="text-danger" href="{% url 'blog:comment_delete' comment.id %}">delete
                                        comment</a>
                                </div>
                                {% endif %}
                            </div>

                        </li>
                        {% endfor %}

                    </ul>
                    {% if request.user.is_authenticated %}
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" method="post" class="bg-light p-4">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'banner.html' with content=banner%}

<section class="ftco-section contact-section ftco-degree">
    <div class="container">
        <div class="row block-9">
            <div class="col-md-4 contact-info ftco-animate bg-light p-4 fadeInUp ftco-animated">
                <div class="row">
                    <div class="col-md-12 mb-4">
                        <h2 class="h4">Contact Information</h2>
                    </div>
                    <div class="col-md-12 mb-3">
                        <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
                    </div>
                    <div class="col-md-12 mb-3">
                        <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                    </div>
                    <div class="col-md-12 mb-3">
                        <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
                    </div>
                    <div class="col-md-12 mb-3">
                        <p><span>Website:</span> <a href="#">yoursite.com</a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-6 ftco-animate fadeInUp ftco-animated">
                <form action="#" class="contact-form">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Your Name">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Your Email">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Subject">
                    </div>
                    <div class="form-group">
                        <textarea name="" id="" cols="30" rows="7" class="form-control"
                            placeholder="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/head.html
{% load static %}
<title>Muscle</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'css/aos.css' %}">

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

{% include 'slider.html' %}


<section class="ftco-section-services ftco-degree">
	<div class="container">
		<div class="row d-flex align-items-center">
			<div class="col-xl-6 d-flex align-self-stretch">
				<div class="align-self-stretch"><img src="{% static 'images/about.jpg' %}" class="img-fluid" alt="">
				</div>
			</div>
			<div class="col-xl-6 align-self-stretch pt-5">
				<div class="row justify-content-center mb-3">
					<div class="col-md-12 heading-section ftco-animate">
						<h3 class="subheading">Shape Your Body</h3>
						<h2 class="mb-4">What We Do?</h2>
					</div>
				</div>
				<div class="services d-flex ftco-animate">
					<div class="icon d-flex justify-content-center align-items-center">
						<span class="flaticon-ruler"></span>
					</div>
					<div class="text ml-5">
						<h3>Analyze Your Goal</h3>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
							It is a paradisematic country</p>
					</div>
				</div>
				<div class="services d-flex ftco-animate">
					<div class="icon d-flex justify-content-center align-items-center">
						<span class="flaticon-gym"></span>
					</div>
					<div class="text ml-5">
						<h3>Work Hard On It</h3>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
							It is a paradisematic country</p>
					</div>
				</div>
				<div class="services d-flex ftco-animate">
					<div class="icon d-flex justify-content-center align-items-center">
						<span class="flaticon-tools-and-utensils"></span>
					</div>
					<div class="text ml-5">
						<h3>Improve Your Performance</h3>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
							It is a paradisematic country</p>
					</div>
				</div>
				<div class="services d-flex ftco-animate">
					<div class="icon d-flex justify-content-center align-items-center">
						<span class="flaticon-abs"></span>
					</div>
					<div class="text ml-5">
						<h3>Achieve Your Perfect Body</h3>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
							It is a paradisematic country</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="ftco-counter ftco-bg-dark img" id="section-counter" style="background-image: url(images/bg_2.jpg);"
	data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-10">
				<div class="row">
					<div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="5000">0</strong>
								<span>Happy Customers</span>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="4560">0</strong>
								<span>Perfect Bodies</span>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="570">0</strong>
								<span>Working Hours</span>
							</div>
						</div>
					</div>
					<div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
						<div class="block-18 text-center">
							<div class="text">
								<strong class="number" data-number="900">0</strong>
								<span>Success Stories</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>


<!-- program section -->
<section class="ftco-section">
	<div class="container-fluid">
		<div class="row justify-content-center mb-5 pb-3">
			<div class="col-md-7 heading-section ftco-animate text-center">
				<h3 class="subheading">Gym Classes</h3>
				<h2 class="mb-1">Workout Classes</h2>
			</div>
		</div>
		<div class="row">
			{% for cat in categories %}
			<div class="col-md-6 col-lg-3">
				<div class="package-program ftco-animate">
					<a href="{% url 'workouts:program_detail' cat.1.1 %}"
						class="img d-flex justify-content-center align-items-center"
						style="background-image: url('{{cat.1.2.url}}');">
						<span>See Exercise</span>
					</a>
					<div class="text mt-3">
						<h3><a href="{% url 'workouts:program_detail' cat.1.1 %}">{{cat.0}}</a></h3>
						<p>A small river named Duden flows by their place and supplies it with the necessary regelialia.
						</p>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<div class="container">
		<div class="row mt-4 justify-content-center ftco-animate">
			<div class="col-md-4 text-center">
				<a href="{% url 'workouts:program' %}" class="btn-custom py-4">View More Program <span
						class="ion-ios-arrow-down ml-2"></span></a>
			</div>
		</div>
	</div>
</section>


<!-- blog recent posts -->
<section class="ftco-section bg-light">
	<div class="container">
		<div class="row justify-content-center mb-5 pb-3">
			<div class="col-md-7 heading-section ftco-animate text-center">
				<h3 class="subheading">Articles</h3>
				<h2 class="mb-1">Recent Blog</h2>
			</div>
		</div>
		<div class="row d-flex">

			{% for post in recent_posts %}
			<div class="col-md-4 d-flex ftco-animate fadeInUp ftco-animated">
				<div class="blog-entry">
					<a href="{{ post.get_absolute_url }}" class="block-20"
						style="background-image: url('{{ post.image.url}}');">
					</a>
					<div class="text p-4 float-right d-block">
						<div class="meta">
							<div><a href="#">{{post.created}}</a></div>
							<div><a href="#">{{post.autor}}</a></div>
							<div><a href="#" class="meta-chat"><span class="icon-chat"></span>
									{{post.comments.count}}</a></div>
						</div>
						<h3 class="heading mt-2"><a href="{{ post.get_absolute_url }}">{{post.title}}</a></h3>
						<p>{{post.content|striptags|truncatechars_html:100}}</p>
					</div>
				</div>
			</div>

			{% endfor %}
		</div>


	</div>
	</div>
</section>

<!-- Instagram gallery -->

<section class="ftco-gallery">
	<div class="container-wrap">
		<div class="row no-gutters">
			<div class="col-md-3 ftco-animate">
				<div class="gallery ftco-gradient d-flex justify-content-center align-items-center">
					<div class="row justify-content-center">
						<div class="col-md-12 heading-section ftco-animate text-center">
							<h3 class="subheading">Gallery Photo</h3>
							<h2 class="mb-1">Instagram</h2>
						</div>
					</div>
				</div>
			</div>
			{% for picture in gallery %}
			<div class="col-md-3 ftco-animate">
				<a href="{{picture.image.url}}" class="gallery image-popup img d-flex align-items-center"
					style="background-image: url('{{picture.image.url}}');">
					<div class="icon mb-4 d-flex align-items-center justify-content-center">
						<span class="icon-instagram"></span>
					</div>
				</a>
			</div>
			{% endfor %}

		</div>
	</div>
</section>
{% endblock content %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand py-2 px-4" href="{% url 'workouts:home' %}">Muscle</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'workouts:home' %}" class="nav-link">Home</a></li>
        {% if request.user.is_authenticated and not request.user.is_staff%}
        <li class="nav-item"><a href="{% url 'workouts:member_page' %}" class="nav-link">See profile</a></li>
        {% endif %}
        <li class="nav-item"><a href="{% url 'workouts:program' %}" class="nav-link">Program</a></li>
        <li class="nav-item"><a href="{% url 'workouts:coach' %}" class="nav-link">Coaches</a></li>
        <li class="nav-item"><a href="{% url 'workouts:about' %}" class="nav-link">About</a></li>
        <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="{% url 'workouts:contact' %}" class="nav-link">Contact</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'workouts:logout_page' %}" class="nav-link">Log out</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'workouts:login_page' %}" class="nav-link">Log in</a></li>
        <li class="nav-item"><a href="{% url 'workouts:register_page' %}" class="nav-link">Sign up</a></li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

templates/program.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include 'banner.html' with content=banner%}

<section class="ftco-degree">
  <div class="container-fluid">
    <!-- title -->
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <h3 class="subheading">Gym Classes</h3>
        <h2 class="mb-1">Workout Classes</h2>
      </div>
    </div>

    <div class="row">
      {% for category in categories %}
      {% if category.exercise_set.count != 0 %}
      <div class="col-md-6 col-lg-3">
        <div class="package-program ftco-animate">
          <a href="{{category.get_absolute_url}}" class="img d-flex justify-content-center align-items-center"
            style="background-image: url('{{ category.image.url}}');">
            <span>See Exercise</span>
          </a>
          <div class="text mt-3">
            <h3><a href="{{category.get_absolute_url}}">{{ category.title}}</a></h3>
            <p>{{ category.description|truncatechars_html:150|striptags }}</p>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}

    </div>
  </div>

  </div>
</section>

{% endblock content %}