blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>', views.blog_detail, name='blog_detail'),
    path('delete/<int:id>', views.comment_delete, name='comment_delete'),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workouts.urls'), name="workouts"),
    path('blog', include('blog.urls'), name="blog"),

    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workouts/urls.py
from django.urls import path

from . import views

app_name = 'workouts'

urlpatterns = [
    path('', views.index, name='home'),
    path('exercise/<int:exercise_id>',
         views.exercise_detail, name='exercise_detail'),

    path('program', views.program, name='program'),
    path('program/<slug:slug>', views.program_detail, name='program_detail'),
    path('coach', views.coach, name='coach'),
    path('coach/<int:coach_id>', views.coach_detail, name='coach_detail'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),

    # Members
    path('register', views.register_page, name='register_page'),
    path('login', views.login_page, name='login_page'),
    path('logout', views.logout_page, name='logout_page'),
    path('member', views.member_page, name='member_page'),
    path('create_workout', views.create_workout, name='create_workout'),
    path('update_workout/<int:id>', views.update_workout, name='update_workout'),
]

templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<section class="hero-wrap" style="background-color:black; height: 125px;">
</section>
<section class="ftco-degree"></section>
<form method="POST" action="">
  {% csrf_token %}
  <div class="container">

    <h1>Log in</h1>
    <form method="POST">
      {% csrf_token %}
      <input type="text" name="username" placeholder="Username" class="form-control">
      <br>
      <input type="password" name="password" placeholder="Password" class="form-control">
      <button class="btn btn-primary" type="submit">Log in</button>
    </form>
    <br><br><br>
  </div>
  </section>
  {% endblock content %}

templates/user/member.html
{% extends 'base.html' %}

{% block content %}
<section class="hero-wrap" style="background-color:black; height: 125px;">
</section>
<section class="ftco-degree"></section>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      {% if request.user.member.profile_pic %}
      <img src="{{ request.user.member.profile_pic.url}}" width="250px" alt=""> <br> <br>
      {% endif %}
      <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-primary" type="submit">Submit</button>
      </form> <br> <br>

    </div>
    <div class="col-sm-8">
      <h2>Hello, {{ member.user|title }}</h2>
      <br> <br>
      Total workouts: {{ total_workouts }} <br>
      Workouts in progress: {{ in_progres }} <br>
      Finished workouts: {{ finished }} <br> <br>
      <a href="{% url 'workouts:create_workout' %}">Add workout</a>
      <br>
    </div>
  </div>
  </section {% for workout in workouts %} <hr>
  <div class="row">
    <div class="col-sm-12 text-center">
      <h1>{{ workout.date_of_training}} Workouts</h1>
      <br><br>
    </div>

    {% for exercise in workout.exercise.all %}
    <div class="col-sm-2">
      <h4>{{ exercise|title }}</h4>

      <p>{{ workout.status|title }}</p>
      <p>{{ workout.name|title }}</p>
      <a href="{% url 'workouts:update_workout'  workout.id %}">Update workout</a>
    </div>
    <div class="col-sm-10">
      {{ exercise.content|safe }}
    </div>

    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="hero-wrap" style="background-color:black; height: 125px;">
</section>

<section class="ftco-degree"></section>
<div class="container">
  <h1>Register</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
</div>
<br><br><br>
</section>
{% endblock content %}